name: Republish

on:
  schedule:
    - cron: '5 2 * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
    - name: trigger pages rebuild
      run: |
          curl --fail --request POST \
            --url  https://api.github.com/repos/alexdawn/alexdawn.github.io/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
      env:
        USER_TOKEN: $